name: Reusable Deployment
on: 
  workflow_call:
    inputs:
      my-artifact-name:
        description: the name of the deployable artifact
        required: false
        default: dist
        type: string
    outputs:
      step-result:
        description: The output description
        value: ${{ jobs.deployment.outputs.outcome }}
    #secrets:
      #some-secrets:
        #required: true



jobs:
  deployment:
    outputs:
      outcome: ${{ steps.set-results.outputs.step-result }}
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.my-artifact-name}}
      - name: Deploy code
        run: echo "Building & Deploying"
      - name: Set result output
        id: set-results
        run: echo "step-result=success" >> $GITHUB_OUTPUT